// src/components/Header.vue
<template>
  <TopBanner />
  <header
    class="w-full h-14 shrink-0 flex flex-row justify-center items-center bg-dark text-light"
  >
    <div
      class="w-full md:max-w-5xl lg:max-w-7xl h-full flex flex-row justify-between items-center px-0 sm:px-4"
    >
      <div class="h-full flex flex-row justify-start items-center">
        <router-link
          class="h-full flex flex-row justify-center items-center px-4 hover:bg-zinc-800"
          to="/"
        >
          <img class="w-7 h-auto" src="/icon.png" />
        </router-link>
        <router-link
          class="h-full flex flex-row justify-center items-center px-4 hover:bg-zinc-800"
          to="/blog"
        >
          <span class="text-light font-semibold">Blog</span>
        </router-link>
        <span
          class="h-full flex flex-row justify-center items-center cursor-pointer font-semibold mr-2 px-3 hover:bg-zinc-800"
          @click="handleSetTokenBtnClick"
        >
          {{ token ? "Edit" : "Add" }} Access Token
        </span>
      </div>
      <div class="hidden h-full md:flex flex-row justify-start items-center">
        <a
          href="https://www.bytebase.com?source=star-history"
          target="_blank"
          class="h-full flex flex-row justify-center items-center px-4 hover:bg-zinc-800"
        >
          <img class="h-6 mt-1 mr-2" src="/craft-by-bytebase.webp" />
        </a>
      </div>
      <div class="h-full hidden md:flex flex-row justify-end items-center">
        <a
          class="h-full flex flex-row justify-center items-center px-2 hover:bg-zinc-800"
          href="https://twitter.com/StarHistoryHQ"
          target="_blank"
        >
          <i class="fab fa-twitter text-2xl text-blue-300"></i>
        </a>
        <a
          class="h-full flex flex-row justify-center items-center px-2 mr-2 hover:bg-zinc-800"
          href="https://discord.gg/yyzsmgcqg7"
          target="_blank"
        >
          <i class="fab fa-discord text-2xl text-indigo-300"></i>
        </a>
        <GitHubStarButton />
      </div>
      <div class="h-full flex md:hidden flex-row justify-end items-center">
        <span
          class="relative h-full w-10 px-3 flex flex-row justify-center items-center cursor-pointer font-semibold text-light hover:bg-zinc-800"
          @click="handleToggleDropMenuBtnClick"
        >
          <span
            class="w-4 transition-all h-px bg-light absolute top-1/2"
            :class="state.showDropMenu ? 'w-6 rotate-45' : '-mt-1'"
          ></span>
          <span
            class="w-4 transition-all h-px bg-light absolute top-1/2"
            :class="state.showDropMenu ? 'hidden' : ''"
          ></span>
          <span
            class="w-4 transition-all h-px bg-light absolute top-1/2"
            :class="state.showDropMenu ? 'w-6 -rotate-45' : 'mt-1'"
          ></span>
        </span>
      </div>
    </div>
  </header>
  <div
    class="`w-full h-auto py-2 flex md:hidden flex-col justify-start items-start shadow-lg border-b"
    :class="state.showDropMenu ? 'flex' : 'hidden'"
  >
    <router-link
      class="h-12 px-3 w-full flex flex-row justify-start items-center cursor-pointer font-semibold text-dark mr-2 hover:bg-gray-100 hover:text-blue-500"
      to="/blog/how-to-use-github-star-history"
    >
      📕 How to use this site
    </router-link>
    <span
      class="h-12 px-3 w-full flex flex-row justify-start items-center cursor-pointer font-semibold text-dark mr-2 hover:bg-gray-100 hover:text-blue-500"
      @click="handleSetTokenBtnClick"
    >
      {{ token ? "Edit" : "Add" }} Access Token
    </span>
    <span class="h-12 px-3 w-full flex flex-row justify-start items-center">
      <a
        class="github-button -mt-1"
        href="https://github.com/star-history/star-history"
        data-show-count="true"
        aria-label="Star star-history/star-history on GitHub"
        target="_blank"
      >
        Star
      </a>
    </span>
  </div>
  <TokenSettingDialog
    v-if="state.showSetTokenDialog"
    @close="handleSetTokenDialogClose"
  />
</template>

<script lang="ts" setup>
import { computed, reactive } from "vue";
import useAppStore from "../store";
import TopBanner from "./TopBanner.vue";
import GitHubStarButton from "./GitHubStarButton.vue";
import TokenSettingDialog from "./TokenSettingDialog.vue";

interface State {
  showDropMenu: boolean;
  showSetTokenDialog: boolean;
}

const store = useAppStore();
const state = reactive<State>({
  showDropMenu: false,
  showSetTokenDialog: false,
});

const token = computed(() => {
  return store.token;
});

const handleSetTokenBtnClick = () => {
  state.showSetTokenDialog = true;
};

const handleSetTokenDialogClose = () => {
  state.showSetTokenDialog = false;
};

const handleToggleDropMenuBtnClick = () => {
  state.showDropMenu = !state.showDropMenu;
};
</script>

// frontend/components/header.tsx
import React, { useState, useEffect } from "react";
import TopBanner from "./TopBanner";
import GitHubStarButton from "./GitHubStarButton";
import TokenSettingDialog from "./TokenSettingDialog";
import Link from "next/link";
import { AppStateProvider, useAppStore } from "../store";

const Header: React.FC = () => {
  const store = useAppStore()
  const [showSetTokenDialog, setShowSetTokenDialog] = useState(false);
  const [headerText, setHeaderText] = useState("Add Access Token");
  const [state, setState] = useState<State>({
    showDropMenu: false,
    showSetTokenDialog: false,
  });

  interface State {
    showDropMenu: boolean;
    showSetTokenDialog: boolean;
    tokenCache?: string;
  }

  const handleSetTokenBtnClick = () => {
    setShowSetTokenDialog(true);
  };

  const handleToggleDropMenuBtnClick = () => {
    setState((prevState) => ({
      ...prevState,
      showDropMenu: !prevState.showDropMenu,
    }));
  };

  const handleSetTokenDialogClose = () => {
    setShowSetTokenDialog(false);
  };

useEffect(() => {
  setHeaderText(store.token ? "Edit Access Token" : "Add Access Token")
}, [store.token]);

  return (
    <>
      {showSetTokenDialog && (
        <TokenSettingDialog
          onClose={handleSetTokenDialogClose}
          tokenCache={false}
        />
      )}

      <AppStateProvider>
        <TopBanner />
        <header className="w-full h-14 shrink-0 flex flex-row justify-center items-center bg-[#363636] text-light">
          <div className="w-full md:max-w-5xl lg:max-w-7xl h-full flex flex-row justify-between items-center px-0 sm:px-4">
            <div className="h-full bg-dark flex flex-row justify-start items-center">
              <Link href="/" className="h-full flex flex-row justify-center items-center px-3 hover:bg-zinc-800">
                <img className="w-7 h-auto" src="/assets/icon.png" alt="Logo" />
              </Link>
              <Link href="/blog"className="h-full flex flex-row justify-center items-center text-base px-3 hover:bg-zinc-800">
                <span className="text-white font-semibold -2">Blog</span>
              </Link>
              <span
                className="h-full flex flex-row justify-center items-center cursor-pointer text-white text-base px-3 font-semibold mr-2 hover:bg-zinc-800"
                onClick={handleSetTokenBtnClick}
              >
                {headerText}
              </span>
            </div>
            <div className="hidden h-full md:flex flex-row justify-start items-center">
              <Link
                href="https://www.bytebase.com/?source=star-history"
                target="_blank"
                rel="noopener noreferrer"
                className="h-full flex text-white text-base flex-row justify-center items-center px-4 hover:bg-zinc-800"
              >
                <img className="h-6 mt-1 mr-2" src="/assets/craft-by-bytebase.webp" alt="" />
              </Link>
            </div>
            <div className="h-full hidden md:flex flex-row justify-end items-center space-x-2">
              <a className="h-full flex flex-row justify-center items-center px-2 hover:bg-zinc-800" href="https://twitter.com/StarHistoryHQ" target="_blank" rel="noopener noreferrer">
                <i className="fab fa-twitter text-2xl text-blue-300"></i>
              </a>
              <a className="h-full flex flex-row justify-center items-center px-2 hover:bg-zinc-800" href="https://rss.beehiiv.com/feeds/BbNzf9ozGZ.xml" target="_blank" rel="noopener noreferrer">
                <i className="fas fa-rss text-2xl text-orange-400"></i>
              </a>
              <GitHubStarButton />
            </div>

            <div className="h-full flex md:hidden flex-row justify-end items-center">
              <span
                className="relative h-full w-10 px-3 flex flex-row justify-center items-center cursor-pointer font-semibold text-light hover:bg-zinc-800"
                onClick={handleToggleDropMenuBtnClick}
              >
                <span className={`w-4 transition-all h-px bg-light absolute top-1/2 ${state.showDropMenu ? "w-6 rotate-45" : "-mt-1"}`}></span>
                <span className={`w-4 transition-all h-px bg-light absolute top-1/2 ${state.showDropMenu ? "hidden" : ""}`}></span>
                <span className={`w-4 transition-all h-px bg-light absolute top-1/2 ${state.showDropMenu ? "w-6 -rotate-45" : "mt-1"}`}></span>
              </span>
            </div>
          </div>
        </header>
        <div className={`w-full h-auto py-2 flex md:hidden flex-col justify-start items-start shadow-lg border-b ${state.showDropMenu ? "flex" : "hidden"}`}>
          <Link
            href="/blog/how-to-use-github-star-history"
            className="h-12 text-base px-3 w-full flex flex-row justify-start items-center cursor-pointer font-semibold text-dark mr-2 hover:bg-gray-100 hover:text-blue-500"
          >
            📕 How to use this site
          </Link>
          <span
            className="h-12 px-3 text-base w-full flex flex-row justify-start items-center cursor-pointer font-semibold text-dark mr-2 hover:bg-gray-100 hover:text-blue-500"
            onClick={handleSetTokenBtnClick}
          >
            {headerText}
          </span>
          <span className="h-12 text-base px-3 w-full flex flex-row justify-start items-center">
            <a
              className="github-button -mt-1"
              href="https://github.com/star-history/star-history"
              data-show-count="true"
              aria-label="Star star-history/star-history on GitHub"
              target="_blank"
              rel="noopener noreferrer"
            >
              Star
            </a>
          </span>
        </div>
      </AppStateProvider>
    </>
  );
};

export default Header;
