// src/components/TopBanner.vue
<template>
  <div
    class="flex justify-center items-center gap-x-6 bg-green-600 px-6 py-1 sm:px-3.5 "
  >
    <p class="text-sm leading-6 text-white">
      <router-link to="/blog/list-your-open-source-project">
        Want to promote your open source project? Be on our ⭐️Starlet
        List⭐️ for FREE&nbsp;<span aria-hidden="true">&rarr;</span>
      </router-link>
    </p>
  </div>
</template>

// frontend/components/TopBanner.tsx
import Link from "next/link";

const TopBanner: React.FC = () => {
    return (
        <nav>
            <div className="flex justify-center items-center gap-x-6 bg-green-600 px-6 py-1 sm:px-3.5 ">
                <p className="text-sm leading-6 text-white">
                    <Link href="/blog/list-your-open-source-project">
                        Want to promote your open source project? Be on our ⭐️Starlet List⭐️ for FREE →
                    </Link>
                </p>
            </div>
        </nav>
    )
}

export default TopBanner
