// src/components/TopBanner.vue
<template>
  <div
    class="flex justify-center items-center gap-x-6 bg-green-600 px-6 py-1 sm:px-3.5 "
  >
    <p class="text-sm leading-6 text-white">
      <a href="https://forum.star-history.com" target="__blank">
        🚀Promote and discover🔍 open source projects ->
      </a>
    </p>
  </div>
</template>

// components/TopBanner.tsx
const TopBanner: React.FC = () => {
    return (
        <nav>
            <div className="flex justify-center items-center gap-x-6 bg-green-600 px-6 py-1 sm:px-3.5 ">
                <p className="text-sm leading-6 text-white">
                <a href="https://forum.star-history.com" target="__blank">
                    🚀Promote and discover🔍 open source projects ->
                </a>
                </p>
            </div>
        </nav>
    )
}

export default TopBanner
